### ISSUE TITLE
Add graphs

### ISSUE THREAD

**Issue by nikhils4** [TheCodeClutch/all-about-covid19#2]
To add the graphs : 

1 - Use this API - [Chart.js](https://www.chartjs.org/docs/latest/charts/mixed.html)

2 - Historic data is coming from API - Store that data in Local Storage for each state

3 - On click on a particular state from the table show the graph related to that state

4 - By default the graph should contain the entire country data 

5 - Position graph on the right-hand side on a desktop device and at the bottom for the mobile device

6 - Four different graphs for each state which includes Total, Active, Recovered and Deceased cases or better you can integrate all of them into one using different color lines

**Comment by mshreya9** [comment]
Fixed #2
